import React from 'react';

const Navigation = () => {
    return (
        <div>
            <h2>This is Navigation</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit eum quaerat labore fuga, quas nulla ullam placeat! Beatae voluptate ipsum neque ut ad fugit accusamus et quam exercitationem? Quam perferendis delectus, ducimus alias eaque inventore, itaque dolorum debitis aspernatur in, vel culpa commodi nesciunt iste. Porro dolore asperiores cumque saepe maiores suscipit laudantium dolorum! Quae quos illo nostrum eveniet necessitatibus assumenda temporibus atque iusto cumque dignissimos sed fugit nam expedita corrupti fugiat, voluptatem dolorum recusandae. Doloribus quidem ratione asperiores? Deleniti quibusdam similique dolore beatae recusandae quia quo est fuga cupiditate. Quas a maiores placeat consectetur, tempora delectus dolorum voluptates eius temporibus beatae. Perspiciatis suscipit quia cumque ab. Eveniet placeat nobis libero impedit quo voluptas, delectus sequi facilis dicta provident asperiores quod corporis dolor commodi voluptatibus accusantium blanditiis ipsam architecto minus quam aliquid nemo dignissimos quia? Beatae nesciunt doloribus atque culpa autem! Commodi, asperiores voluptatum. Atque, nemo ab? Facere, exercitationem eaque ipsam suscipit iure saepe placeat aliquam temporibus maxime praesentium explicabo inventore dignissimos vero pariatur itaque? Unde, suscipit officia! Vel, similique. Ullam laboriosam, error autem itaque placeat id facilis accusamus voluptatem blanditiis deserunt voluptatum, corrupti quaerat soluta eum hic eos officiis asperiores aliquam fuga distinctio quas, qui ad fugiat animi. Sed perferendis, dolores nobis distinctio doloremque laboriosam quia quos molestiae id saepe vitae voluptas neque iusto ipsa, nihil architecto possimus harum vero facilis sequi voluptatum assumenda corrupti, consequatur ratione. Illo pariatur, omnis quos numquam magni placeat, exercitationem consectetur repudiandae nobis nemo quam recusandae doloremque voluptas mollitia qui dolor deleniti vel vitae voluptate tempora dicta officiis minus saepe. Dolorum, obcaecati odio laboriosam eligendi sed voluptates aliquid provident saepe adipisci accusantium officia cumque, ratione voluptas minus ea fuga neque rerum at exercitationem odit expedita error similique reiciendis. Minima, provident? In deleniti voluptatibus facere, aperiam saepe porro culpa ea consectetur. Voluptatem repellendus ipsam explicabo!</p>
        </div>
    );
};

export default Navigation;